---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: application
spec:
  protocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  selector:
    app: application
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      serviceAccountName: application
      containers:
      - name: application
        image: nicholasjackson/fake-service:v0.26.0
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "UPSTREAM_URIS"
          value: "http://database.virtual.prod-eu-west-1-default.consul"
        - name: "NAME"
          value: "application-us-west-2"
        - name: "MESSAGE"
          value: "Response from application in us-west-2"
# ---
# apiVersion: consul.hashicorp.com/v1alpha1
# kind: ExportedServices
# metadata:
#   name: default
# spec:
#   services:
#     - name: application
#       consumers:
#       - peer: prod-us-east-1
# ---
# apiVersion: consul.hashicorp.com/v1alpha1
# kind: ServiceIntentions
# metadata:
#   name: application
# spec:
#   destination:
#     name: application
#   sources:
#    - name: web
#      action: allow
#      peer: prod-us-east-1
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: database
spec:
  destination:
    name: "database"
  sources:
  - name: "application"
    action: allow