---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-api-gateway
  namespace: consul
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: consul-api-gateway-token
  namespace: consul
  annotations:
    kubernetes.io/service-account.name: consul-api-gateway
type: kubernetes.io/service-account-token