global:
  enabled: false
  name: consul
  metrics:
    enabled: true
    enableAgentMetrics: true
  peering:
    enabled: true

controller:
  enabled: true

terminatingGateways:
  enabled: true
  defaults:
    replicas: 1

meshGateway:
  enabled: true
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer
    annotations: |
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"

connectInject:
  replicas: 1
  enabled: true
  consulNamespaces:
    mirroringK8S: true
  metrics:
    defaultEnabled: true
  apiGateway:
    manageExternalCRDs: true
    managedGatewayClass:
      serviceType: LoadBalancer