global:
  enabled: false
  name: consul
  metrics:
    enabled: true
    enableAgentMetrics: true
  peering:
    enabled: true

controller:
  enabled: true

terminatingGateways:
  enabled: true
  defaults:
    replicas: 1

meshGateway:
  enabled: true
  replicas: 1

connectInject:
  replicas: 1
  enabled: true
  consulNamespaces:
    mirroringK8S: true
  metrics:
    defaultEnabled: true
  apiGateway:
    manageExternalCRDs: true
    managedGatewayClass:
      serviceType: LoadBalancer