global:
  enabled: false
  name: consul
  metrics:
    enabled: true
    enableAgentMetrics: true
  peering:
    enabled: true
  adminPartitions:
    enabled: true
    name: "eks"
  enableConsulNamespaces: true

controller:
  enabled: true

terminatingGateways:
  enabled: true
  defaults:
    replicas: 1

meshGateway:
  enabled: true
  replicas: 1
  service:
    enabled: true
    type: LoadBalancer
    annotations: |
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip

connectInject:
  replicas: 1
  enabled: true
  consulNamespaces:
    mirroringK8S: true
  metrics:
    defaultEnabled: true
  apiGateway:
    manageExternalCRDs: true
    managedGatewayClass:
      serviceType: LoadBalancer
      copyAnnotations:
        service:
          annotations: |
            - service.beta.kubernetes.io/aws-load-balancer-type
            - service.beta.kubernetes.io/aws-load-balancer-nlb-target-type